title: Data Diary
author: uowol
email: alllhvhla@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This blog is related to Statistics, Data-Science, Machine-Learning, and some TMIs.
  Thank you for visiting my blog :b
show_excerpts: true # set to true to show excerpts on the homepage

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Bread Factory
  tagline: Create some exciting things everyday.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: uowol

  # generate social links in footer
  social_links:
    twitter: uowol
    github:  uowol
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed